import warnings
from LysQt.QtCore import pyqtSignal
from lys.errors import NotImplementedWarning

from .SaveCanvas import saveCanvas
from .AnnotationData import AnnotationWithLine


class RegionAnnotation(AnnotationWithLine):
    """
    Interface to access region annotations in canvas.

    *RegionAnnotation* is usually generated by addRegionAnnotation method in canvas.

    Several methods related to the appearance of line is inherited from :class:`.AnnotationData.AnnotationWithLine`

    Args:
        canvas(Canvas): canvas to which the line annotation is added.
        region(length 2 sequence): The region of the annotation in the form of (x1, x2).
        axis('BottomLeft', 'BottomRight', 'TopLeft', or 'TopRight'): The axis to which the line annotation is added.

    Example::

        from lys import display
        g = display()
        rect = g.canvas.addRegionAnnotation()
        rect.setLineColor("#ff0000")
    """
    changed = pyqtSignal()
    """PyqtSignal that is emitted when the region is changed."""

    def __init__(self, canvas, region, orientation, axis):
        super().__init__(canvas, "test", axis)
        self._region = region
        self._orientation = orientation

    @saveCanvas
    def setRegion(self, region):
        """
        Set region of the annotation.

        Args:
            region(length 2 sequence): The region of rectangle in the form of (x1, x2)
        """
        r = (min(*region), max(*region))
        self._setRegion(r)
        self._region = r

    def getRegion(self):
        """
        Get the region of the annotation.

        Return:
            length 2 sequence: The region of annotation in the form of (x1, x2)
        """
        return self._region

    def getOrientation(self):
        """
        Get the orientation of the annotation.

        Return:
            str: The orientation of annotation ('vertical' or 'horizontal')
        """
        return self._orientation

    def _setRegion(self, region):
        warnings.warn(str(type(self)) + " does not implement _setRegion(region) method.", NotImplementedWarning)
