import warnings
from LysQt.QtCore import pyqtSignal
from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .AnnotationData import AnnotationData


class TextAnnotation(AnnotationData):
    """
    Interface to access text annotations in canvas.

    *TextAnnotation* is usually generated by addText method in canvas.

    Args:
        canvas(Canvas): canvas to which the text annotation is added.
        text(str): The text of the annotation.
        axis('BottomLeft', 'BottomRight', 'TopLeft', or 'TopRight'): The axis to which the text annotation is added.

    Example::

        from lys import display
        g = display()
        line = g.addText('test')
    """

    edited = pyqtSignal(str)
    """Pyqtsignal that is emitted when the text is edited."""

    def __init__(self, canvas, text, pos, axis):
        super().__init__(canvas, "test", axis)
        self._initialize(text, pos, axis)
        self._text = ""
        self.setText(text)
        self.setPosition(pos)

    @saveCanvas
    def setText(self, text):
        """
        Set the text of the annotation.

        Args:
            text(str): The text of the annotation.
        """
        if text != self._text:
            self._setText(text)
            self._text = text
            self.edited.emit(text)

    def getText(self):
        """
        Get the text of the annotation.

        Return:
            str: The text of the annotation.
        """
        return self._text

    @saveCanvas
    def setPosition(self, pos):
        """
        Set the position of the annotation.

        Args:
            pos(length 2 sequence): The position of the annotation.
        """
        self._setPosition(pos)
        self._pos = pos

    def getPosition(self):
        """
        Get the position of the annotation.

        Args:
            length 2 sequence: The position of the annotation.
        """
        return self._pos

    def _loadAppearance(self, appearance):
        pass

    def _initialize(self, text, axis):
        warnings.warn(str(type(self)) + " does not implement _initialize(text, axis) method.", NotImplementedWarning)

    def _setText(self, text):
        warnings.warn(str(type(self)) + " does not implement _setText(text) method.", NotImplementedWarning)

    def _setPosition(self, pos):
        warnings.warn(str(type(self)) + " does not implement _setPosition(pos) method.", NotImplementedWarning)
