import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import MeshData3D


class LineData(MeshData3D):
    """
    Interface to access line data in the canvas.

    Most of methods are defined in :class:`.WaveData.MeshData3D`

    Instance of LineData is automatically generated by display or append methods.

    """
    pass