import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import WaveData3D


class PointData(WaveData3D):
    """
    Interface to access line data in the canvas.

    Instance of LineData is automatically generated by display or append methods.

    """
    @saveCanvas
    def setColor(self, color=None, type="scalars"):
        self.__setAppearance("colorType", type)
        self.__setAppearance("color", color)
        self._setColor(color, type)

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    def _loadAppearance(self, appearance):
        pass

    def _setColor(self, color, type):
        warnings.warn(str(type(self)) + " does not implement _setColor(color, type) method.", NotImplementedWarning)
