import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import MeshData3D


class VolumeData(MeshData3D):
    """
    Interface to access volume data in the canvas.

    Instance of VolumeData is automatically generated by display or append methods.

    """

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    def _loadAppearance(self, appearance):
        pass
