import warnings

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import MeshData3D


class VolumeData(MeshData3D):
    """
    Interface to access volume data in the canvas.

    Most of methods are defined in :class:`.WaveData.MeshData3D`

    Instance of VolumeData is automatically generated by display or append methods.

    """
    pass
